language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libgirepository1.0-dev

install:
  - pip install -r requirements.txt

script:
  - pyinstaller --onefile dropship.py
